# Generated by Django 2.2.6 on 2019-10-27 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='home',
            name='currencyName',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='home',
            name='currencyPrice',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='home',
            name='name',
            field=models.CharField(default='', max_length=100),
        ),
    ]
